// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJJR1CZq-dT2CaR4iVucRUiHAZRxSHdTw',
    appId: '1:576028167504:web:762a3911530739f816b055',
    messagingSenderId: '576028167504',
    projectId: 'luna-d41b9',
    authDomain: 'luna-d41b9.firebaseapp.com',
    storageBucket: 'luna-d41b9.firebasestorage.app',
    measurementId: 'G-VRM06XPXPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ScPdNRb53lojlAr1anOhBecqLckNfEI',
    appId: '1:576028167504:android:8f84ef1b642ec1cf16b055',
    messagingSenderId: '576028167504',
    projectId: 'luna-d41b9',
    storageBucket: 'luna-d41b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaAtrUlv_7ZithfrAu2b_Imum-x3b45Io',
    appId: '1:576028167504:ios:59951d30ac57592116b055',
    messagingSenderId: '576028167504',
    projectId: 'luna-d41b9',
    storageBucket: 'luna-d41b9.firebasestorage.app',
    iosBundleId: 'com.example.luna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaAtrUlv_7ZithfrAu2b_Imum-x3b45Io',
    appId: '1:576028167504:ios:59951d30ac57592116b055',
    messagingSenderId: '576028167504',
    projectId: 'luna-d41b9',
    storageBucket: 'luna-d41b9.firebasestorage.app',
    iosBundleId: 'com.example.luna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJJR1CZq-dT2CaR4iVucRUiHAZRxSHdTw',
    appId: '1:576028167504:web:bdffe822fc5e8bd916b055',
    messagingSenderId: '576028167504',
    projectId: 'luna-d41b9',
    authDomain: 'luna-d41b9.firebaseapp.com',
    storageBucket: 'luna-d41b9.firebasestorage.app',
    measurementId: 'G-4R533L1ND6',
  );
}
